queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci
    batch_size: 1
    merge_method: merge
    max_checks_retries: 1
pull_request_rules:
  - name: queue on approval+label
    conditions:
      - "#approved-reviews-by>=1"
      - label=queue-me
    actions:
      queue:
        name: default
